In [97]:
import numpy as np
np.random.seed(4)
#gaussian distribution sampler: normal(mean=0.0, variance_sqrt=1.0, size=None) s = np.random.normal(0,1)
#teacher model
#randomly generate z=(x,y) with x evenly sampled from (0,10) and y = 1.5 x + 5, a random noise is added. A total of N samples are drawn.
N = 2
X=np.random.rand(N,1)*10
Y=X*1.5+np.random.normal(0,0.1,(N,1))+5
X=np.concatenate((X,np.ones((N,1))),axis=1)
Z=np.concatenate((X,Y),axis=1)
Z

array([[ 9.67029839,  1.        , 19.40585669],
       [ 5.47232249,  1.        , 13.27784359]])

In [98]:
#empirical risk
#L_S(w,Z)
def L_S(w,Z):
    w = np.append(-w,1)
    diff = Z.dot(w.T)
    Nloss = diff.dot(diff)
    return Nloss/N

def test1(k,b,Z):
    return np.sum((Z[:,2]-Z[:,0]*k-b)**2)/N

def grad_L_S(w,Z):
    w = np.append(-w,1)
    diff = Z.dot(w.T)
    return -2/N*diff.dot(Z)[0:2]

def test2(k,b,Z):
    return -2/N*(Z[:,2]-Z[:,0]*k-b).dot(Z[:,0])

t1 = np.array([1.5,10])
grad_L_S(t1,Z)


array([76.29661859, 10.03023104])

In [99]:
#minus log distribution: f
#prar beta
beta = 100
#para sigma
sigma = 10
def f(w): #todo
    return beta*L_S(w,Z)+(1/2/sigma**2)*(w.dot(w))

def grad_f(w):
    grad = beta*grad_L_S(w,Z)+1/sigma**2*w
    return grad

grad_f(t1)

array([7629.67685911, 1003.12310423])

In [100]:
#MCMC
#stepsize h(h*beta=0.01)
h = 0.0001
w = np.ones(2)
for i in range(5000):
    grad_f_w = grad_f(w)
    proposal_state = w-h*grad_f_w+np.random.normal(0,2*h,2)
    reject_thresh = min(1,np.exp(f(w)-f(proposal_state)+(1/4/h)*(np.linalg.norm(proposal_state-w+h*grad_f_w)**2-np.linalg.norm(w-proposal_state+h*grad_f(proposal_state))**2)))
    U = np.random.rand(1)
    if U <= reject_thresh:
        w = proposal_state
w

C:\Users\lenovo\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  


array([1.46066577, 5.28134579])